const CREATED = 201;
const ERROR_CODE = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const CONFLICT = 409;
const SERVER_ERROR = 500;

module.exports = { CREATED, ERROR_CODE, NOT_FOUND, CONFLICT, SERVER_ERROR, UNAUTHORIZED };
